modLoader="javafml"
loaderVersion="[2,)"
license="Creative Commons Zero v1.0 Universal"
issueTrackerURL="https://docs.google.com/forms/d/1B_7RSgaBO8zphI8K-QgTZ1Y4tMWINRAnSexa93IH0_s"

[[mods]]
modId="presencium"
version="2.0"
displayName="Presencium"
displayURL="https://modrinth.com/mod/presencium"
authors="splittque"
logoFile="icon.png"
description='''Minecraft status in discord!'''

[[dependencies.presencium]]
modId="neoforge"
type="required"
versionRange="[20.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.presencium]]
modId="minecraft"
type="required"
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"