modLoader="javafml"
loaderVersion="[0,)"
license="Creative Commons Zero v1.0 Universal"
issueTrackerURL="https://docs.google.com/forms/d/1B_7RSgaBO8zphI8K-QgTZ1Y4tMWINRAnSexa93IH0_s"

[[mods]]
modId="presencium"
version="1.1"
displayName="Presencium"
displayURL="https://modrinth.com/mod/presencium"
authors="splittque"
logoFile="icon.png"
description='''Minecraft status in discord!'''

[[dependencies.presencium]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.presencium]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
